---
- name: Configurar arquivo /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{item}}"
  with_items:
    - 192.168.10.10 controlplane controlplane.kubernetes.local
    - 192.168.10.11 vm-controlplane1 vm-controlplane1.kubernetes.local
    - 192.168.10.12 vm-controlplane2 vm-controlplane2.kubernetes.local
    - 192.168.10.13 vm-controlplane3 vm-controlplane3.kubernetes.local
    - 192.168.10.16 vm-worker1 vm-worker1.kubernetes.local
    - 192.168.10.17 vm-worker2 vm-worker2.kubernetes.local
