- name: "Executar configuração básica do SO"
  hosts: controlplane worker
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  roles:
    - config-default-so
    - vim-config

- name: "Instalar containerd, kubelet e ferramentas do kubernetes"
  hosts: controlplane worker
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  roles:
    - containerd
    - kubernetes-common

- name: "Inicializar o cluster no primeiro controlplane"
  hosts: vm-controlplane1
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  roles:
    - kubernetes-init
