---
- name: Variáveis utilizadas para inicializar o cluster Kubernetes
  debug:
    msg:
      - "ansible_host = {{ ansible_host }}"
      - "ansible_hostname = {{ ansible_hostname }}"
      - "VM_CONTROL_PLANE_ENDPOINT = {{ VM_CONTROL_PLANE_ENDPOINT }}"
      - "VM_POD_NETWORK_CIDR = {{ VM_POD_NETWORK_CIDR }}"
      - "VM_SERVICE_CIDR = {{ VM_SERVICE_CIDR }}"
      - "VM_VIRTUAL_IP = {{ VM_VIRTUAL_IP }}"

- name: Executar o kubeadm init para criar o cluster
  shell: |
    kubeadm init --apiserver-advertise-address={{ ansible_host }} \
    --control-plane-endpoint {{ VM_CONTROL_PLANE_ENDPOINT }} \
    --upload-certs  \
    --node-name {{ ansible_hostname }} \ 
    --pod-network-cidr={{ VM_POD_NETWORK_CIDR }} \ 
    --service-cidr={{ VM_SERVICE_CIDR }} \ 
    --apiserver-cert-extra-sans={{ VM_VIRTUAL_IP }},{{ ansible_host }},{{ ansible_hostname }} \ 
    --cri-socket unix:///run/containerd/containerd.sock
  args:
    executable: /bin/bash
  register: kubeadm_init

- debug: msg="{{ kubeadm_init.stdout }}"