- name: "Cadastrar os nodes no arquivo /etc/hosts"
  hosts: controlplane worker
  user: vagrant
  become: yes
  tasks:
    - name: Configurar hosts ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - "192.168.10.11   vm-controlplane1"
        - "192.168.10.12   vm-controlplane2"
        - "192.168.10.13   vm-controlplane3"
        - "192.168.10.16   vm-worker1"
        - "192.168.10.17   vm-worker2"

